apiVersion: v1
kind: Namespace
metadata:
  name: webhook
---
kind: Service
apiVersion: v1
metadata:
  name: webhook
  namespace: webhook
spec:
  selector:
    app: webhook
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webhook
  namespace: webhook
  name: webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webhook
  template:
    metadata:
      labels:
        app: webhook
      name: webhook
    spec:
      containers:
        - name: webhook
          image: valadwebhook:3
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - readOnly: true
              mountPath: /certs
              name: webhook-certs
      volumes:
        - name: webhook-certs
          secret:
            secretName: webhook-certs
